      ******************************************************************
      * GENERATED by tools/gen-ksds-io.py from cobol/nightly-batch/job.json  *
      * Do not edit: stand-in for IDCAMS REPRO (load).
      * Dataset TRANCATG: lrecl=60 key=(0,6)
      ******************************************************************
       IDENTIFICATION DIVISION.
       PROGRAM-ID. LOAD-TRANCATG.
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT SEQIN ASSIGN TO SEQIN
               ORGANIZATION IS SEQUENTIAL
               FILE STATUS IS WS-SEQ-STATUS.
           SELECT KSDS ASSIGN TO KSDS
               ORGANIZATION IS INDEXED
               ACCESS MODE IS RANDOM
               RECORD KEY IS K-KEY
               FILE STATUS IS WS-KSDS-STATUS.
       DATA DIVISION.
       FILE SECTION.
       FD  SEQIN.
       01  S-REC PIC X(60).
       FD  KSDS.
       01  K-REC.
           05  K-KEY PIC X(6).
           05  FILLER PIC X(54).
       WORKING-STORAGE SECTION.
       01  WS-SEQ-STATUS   PIC XX.
       01  WS-KSDS-STATUS  PIC XX.
       01  WS-EOF          PIC X VALUE 'N'.
       01  WS-COUNT        PIC 9(09) VALUE 0.
       01  WS-RC           PIC 9(02) VALUE 0.
       PROCEDURE DIVISION.
       MAIN.
           OPEN INPUT SEQIN
           IF WS-SEQ-STATUS NOT = '00'
              DISPLAY 'LOAD-TRANCATG: OPEN SEQIN FAILED STATUS '
                      WS-SEQ-STATUS
              MOVE 12 TO RETURN-CODE
              GOBACK
           END-IF
           OPEN OUTPUT KSDS
           IF WS-KSDS-STATUS NOT = '00'
              DISPLAY 'LOAD-TRANCATG: OPEN KSDS FAILED STATUS '
                      WS-KSDS-STATUS
              MOVE 12 TO RETURN-CODE
              GOBACK
           END-IF
           PERFORM UNTIL WS-EOF = 'Y'
              READ SEQIN
                 AT END MOVE 'Y' TO WS-EOF
                 NOT AT END
                    MOVE S-REC TO K-REC
                    WRITE K-REC
                       INVALID KEY
                          DISPLAY 'LOAD-TRANCATG: DUPLICATE KEY ' K-KEY
                             ' STATUS ' WS-KSDS-STATUS
                          MOVE 8 TO WS-RC
                       NOT INVALID KEY
                          ADD 1 TO WS-COUNT
                    END-WRITE
              END-READ
           END-PERFORM
           CLOSE SEQIN KSDS
           DISPLAY 'LOAD-TRANCATG: LOADED ' WS-COUNT ' RECORDS'
           MOVE WS-RC TO RETURN-CODE
           GOBACK.
