      ******************************************************************
      * GENERATED by tools/gen-ksds-io.py from cobol/nightly-batch/job.json  *
      * Do not edit: stand-in for IDCAMS REPRO (unload).
      * Dataset ACCTFILE: lrecl=300 key=(0,11)
      ******************************************************************
       IDENTIFICATION DIVISION.
       PROGRAM-ID. UNLD-ACCTFILE.
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT KSDS ASSIGN TO KSDS
               ORGANIZATION IS INDEXED
               ACCESS MODE IS SEQUENTIAL
               RECORD KEY IS K-KEY
               FILE STATUS IS WS-KSDS-STATUS.
           SELECT SEQOUT ASSIGN TO SEQOUT
               ORGANIZATION IS SEQUENTIAL
               FILE STATUS IS WS-SEQ-STATUS.
       DATA DIVISION.
       FILE SECTION.
       FD  KSDS.
       01  K-REC.
           05  K-KEY PIC X(11).
           05  FILLER PIC X(289).
       FD  SEQOUT.
       01  S-REC PIC X(300).
       WORKING-STORAGE SECTION.
       01  WS-SEQ-STATUS   PIC XX.
       01  WS-KSDS-STATUS  PIC XX.
       01  WS-EOF          PIC X VALUE 'N'.
       01  WS-COUNT        PIC 9(09) VALUE 0.
       PROCEDURE DIVISION.
       MAIN.
           OPEN INPUT KSDS
           IF WS-KSDS-STATUS NOT = '00'
              DISPLAY 'UNLD-ACCTFILE: OPEN KSDS FAILED STATUS '
                      WS-KSDS-STATUS
              MOVE 12 TO RETURN-CODE
              GOBACK
           END-IF
           OPEN OUTPUT SEQOUT
           IF WS-SEQ-STATUS NOT = '00'
              DISPLAY 'UNLD-ACCTFILE: OPEN SEQOUT FAILED STATUS '
                      WS-SEQ-STATUS
              MOVE 12 TO RETURN-CODE
              GOBACK
           END-IF
           PERFORM UNTIL WS-EOF = 'Y'
              READ KSDS NEXT RECORD
                 AT END MOVE 'Y' TO WS-EOF
                 NOT AT END
                    MOVE K-REC TO S-REC
                    WRITE S-REC
                    ADD 1 TO WS-COUNT
              END-READ
           END-PERFORM
           CLOSE KSDS SEQOUT
           DISPLAY 'UNLD-ACCTFILE: UNLOADED ' WS-COUNT ' RECORDS'
           GOBACK.
