#!/usr/bin/env python3
"""gen-ksds-io.py — generate KSDS loader / unloader COBOL programs from job.json.

On the mainframe, VSAM clusters are populated with IDCAMS REPRO and backed up
the same way. GnuCOBOL has no IDCAMS, so each KSDS dataset in a job manifest
gets two tiny generated programs:

    LOAD-<DS>   sequential (fixed-length) file  ->  INDEXED file   (REPRO in)
    UNLD-<DS>   INDEXED file  ->  sequential (fixed-length) file   (REPRO out / backup)

Only the executables actually named in `build.executables` of the manifest are
generated, so the manifest stays the single source of truth. Generated sources
live in cobol/<module>/src/ksds/ and start with a "GENERATED" banner.

Usage:
    ./tools/gen-ksds-io.py <module>            # (re)generate
    ./tools/gen-ksds-io.py <module> --check    # exit 1 if generated files are out of date
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import jobman  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent

BANNER = """      ******************************************************************
      * GENERATED by tools/gen-ksds-io.py from cobol/{module}/job.json  *
      * Do not edit: stand-in for IDCAMS REPRO ({what}).
      * Dataset {ds}: lrecl={lrecl} key=({koff},{klen}){alt}
      ******************************************************************
"""


def record_layout(prefix: str, lrecl: int, key: list[int], alt_keys: list[list[int]]) -> str:
    """01-level record(s) under the FD: one view per key so every key is a
    named field. Multiple 01 entries under one FD share storage (implicit
    REDEFINES), which is exactly what we need."""
    def view(name: str, field: str, off: int, length: int) -> str:
        lines = [f"       01  {name}."]
        if off > 0:
            lines.append(f"           05  FILLER PIC X({off}).")
        lines.append(f"           05  {field} PIC X({length}).")
        rest = lrecl - off - length
        if rest > 0:
            lines.append(f"           05  FILLER PIC X({rest}).")
        return "\n".join(lines)

    out = [view(f"{prefix}-REC", f"{prefix}-KEY", key[0], key[1])]
    for i, (aoff, alen) in enumerate(alt_keys, start=1):
        out.append(view(f"{prefix}-ALT-VIEW-{i}", f"{prefix}-ALT-{i}", aoff, alen))
    return "\n".join(out)


def select_ksds(lrecl: int, access: str, alt_keys: list[list[int]]) -> str:
    alt = "".join(f"\n               ALTERNATE RECORD KEY IS K-ALT-{i}" for i in range(1, len(alt_keys) + 1))
    return f"""           SELECT KSDS ASSIGN TO KSDS
               ORGANIZATION IS INDEXED
               ACCESS MODE IS {access}
               RECORD KEY IS K-KEY{alt}
               FILE STATUS IS WS-KSDS-STATUS."""


def gen_load(module: str, ds_name: str, ds: dict) -> str:
    lrecl, key, alt = ds["lrecl"], ds["key"], ds.get("alt_keys", [])
    alt_txt = " alt=" + ",".join(f"({a},{b})" for a, b in alt) if alt else ""
    return BANNER.format(module=module, what="load", ds=ds_name, lrecl=lrecl, koff=key[0], klen=key[1], alt=alt_txt) + f"""       IDENTIFICATION DIVISION.
       PROGRAM-ID. LOAD-{ds_name}.
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT SEQIN ASSIGN TO SEQIN
               ORGANIZATION IS SEQUENTIAL
               FILE STATUS IS WS-SEQ-STATUS.
{select_ksds(lrecl, "RANDOM", alt)}
       DATA DIVISION.
       FILE SECTION.
       FD  SEQIN.
       01  S-REC PIC X({lrecl}).
       FD  KSDS.
{record_layout("K", lrecl, key, alt)}
       WORKING-STORAGE SECTION.
       01  WS-SEQ-STATUS   PIC XX.
       01  WS-KSDS-STATUS  PIC XX.
       01  WS-EOF          PIC X VALUE 'N'.
       01  WS-COUNT        PIC 9(09) VALUE 0.
       01  WS-RC           PIC 9(02) VALUE 0.
       PROCEDURE DIVISION.
       MAIN.
           OPEN INPUT SEQIN
           IF WS-SEQ-STATUS NOT = '00'
              DISPLAY 'LOAD-{ds_name}: OPEN SEQIN FAILED STATUS '
                      WS-SEQ-STATUS
              MOVE 12 TO RETURN-CODE
              GOBACK
           END-IF
           OPEN OUTPUT KSDS
           IF WS-KSDS-STATUS NOT = '00'
              DISPLAY 'LOAD-{ds_name}: OPEN KSDS FAILED STATUS '
                      WS-KSDS-STATUS
              MOVE 12 TO RETURN-CODE
              GOBACK
           END-IF
           PERFORM UNTIL WS-EOF = 'Y'
              READ SEQIN
                 AT END MOVE 'Y' TO WS-EOF
                 NOT AT END
                    MOVE S-REC TO K-REC
                    WRITE K-REC
                       INVALID KEY
                          DISPLAY 'LOAD-{ds_name}: DUPLICATE KEY ' K-KEY
                             ' STATUS ' WS-KSDS-STATUS
                          MOVE 8 TO WS-RC
                       NOT INVALID KEY
                          ADD 1 TO WS-COUNT
                    END-WRITE
              END-READ
           END-PERFORM
           CLOSE SEQIN KSDS
           DISPLAY 'LOAD-{ds_name}: LOADED ' WS-COUNT ' RECORDS'
           MOVE WS-RC TO RETURN-CODE
           GOBACK.
"""


def gen_unld(module: str, ds_name: str, ds: dict) -> str:
    lrecl, key, alt = ds["lrecl"], ds["key"], ds.get("alt_keys", [])
    alt_txt = " alt=" + ",".join(f"({a},{b})" for a, b in alt) if alt else ""
    return BANNER.format(module=module, what="unload", ds=ds_name, lrecl=lrecl, koff=key[0], klen=key[1], alt=alt_txt) + f"""       IDENTIFICATION DIVISION.
       PROGRAM-ID. UNLD-{ds_name}.
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
{select_ksds(lrecl, "SEQUENTIAL", alt)}
           SELECT SEQOUT ASSIGN TO SEQOUT
               ORGANIZATION IS SEQUENTIAL
               FILE STATUS IS WS-SEQ-STATUS.
       DATA DIVISION.
       FILE SECTION.
       FD  KSDS.
{record_layout("K", lrecl, key, alt)}
       FD  SEQOUT.
       01  S-REC PIC X({lrecl}).
       WORKING-STORAGE SECTION.
       01  WS-SEQ-STATUS   PIC XX.
       01  WS-KSDS-STATUS  PIC XX.
       01  WS-EOF          PIC X VALUE 'N'.
       01  WS-COUNT        PIC 9(09) VALUE 0.
       PROCEDURE DIVISION.
       MAIN.
           OPEN INPUT KSDS
           IF WS-KSDS-STATUS NOT = '00'
              DISPLAY 'UNLD-{ds_name}: OPEN KSDS FAILED STATUS '
                      WS-KSDS-STATUS
              MOVE 12 TO RETURN-CODE
              GOBACK
           END-IF
           OPEN OUTPUT SEQOUT
           IF WS-SEQ-STATUS NOT = '00'
              DISPLAY 'UNLD-{ds_name}: OPEN SEQOUT FAILED STATUS '
                      WS-SEQ-STATUS
              MOVE 12 TO RETURN-CODE
              GOBACK
           END-IF
           PERFORM UNTIL WS-EOF = 'Y'
              READ KSDS NEXT RECORD
                 AT END MOVE 'Y' TO WS-EOF
                 NOT AT END
                    MOVE K-REC TO S-REC
                    WRITE S-REC
                    ADD 1 TO WS-COUNT
              END-READ
           END-PERFORM
           CLOSE KSDS SEQOUT
           DISPLAY 'UNLD-{ds_name}: UNLOADED ' WS-COUNT ' RECORDS'
           GOBACK.
"""


def expected_files(module: str, m: dict) -> dict[Path, str]:
    """{path: content} for every LOAD-/UNLD- executable named in the manifest."""
    out: dict[Path, str] = {}
    ksds_dir = REPO_ROOT / "cobol" / module / "src" / "ksds"
    for name in m["build"]["executables"]:
        for prefix, gen in (("LOAD-", gen_load), ("UNLD-", gen_unld)):
            if name.startswith(prefix):
                ds_name = name[len(prefix):]
                ds = m["datasets"].get(ds_name)
                if ds is None or ds.get("org") != "ksds":
                    raise SystemExit(f"{name}: '{ds_name}' is not a ksds dataset in the manifest")
                out[ksds_dir / f"{name}.cbl"] = gen(module, ds_name, ds)
    return out


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2
    module = argv[1]
    check = "--check" in argv[2:]
    m = jobman.load(module)
    files = expected_files(module, m)
    drift = 0
    for path, content in files.items():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        drift += 1
        if check:
            print(f"OUT OF DATE: {path.relative_to(REPO_ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path.relative_to(REPO_ROOT)}")
    if check:
        print(f"{module}: {len(files)} generated programs, {drift} out of date")
        return 1 if drift else 0
    print(f"{module}: {len(files)} generated programs ({drift} written)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
